spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/user
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
  writer-with-order-by-keys: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    security:
      enabled: false

#logging.level:
  #org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: integration-test
  datasource:
    url: jdbc:postgresql://localhost:5432/user
